### ISSUE TITLE
实现速度控制

### ISSUE THREAD

**Issue by woxiangquca** [sebuaa2019/Team201#1]
速度控制具体在哪个包里实现，订阅的话题名称和速度类型是什么？

**Comment by woxiangquca** [comment]
查看手册里的速度控制demo，可以发现订阅速度消息的话题是/cmd_vel，消息类型是geometry_msgs，实现速度的订阅和底层实现的是wpb_bingup包内的核心节点

**Comment by sbs384** [comment]
查看手册里的速度控制demo，可以发现订阅速度消息的话题是/cmd_vel，消息类型是geometry_msgs，实现速度的订阅和底层实现的是wpb_bingup包内的核心节点
