### ISSUE TITLE
雷达信息获取

### ISSUE THREAD

**Issue by sbs384** [sebuaa2019/Team201#3]
如何辨别雷达的转向和range数组元素对应的角度，角度分辨率手册说是0.9，但是不能整除360，需要测试一下吧？

**Comment by woxiangquca** [comment]
可以写一个小的demo，输出range数组大小，360/数组大小就是角度分辨率；输出range[0],range[89],range[179],range[269]对应的障碍物距离信息，分别遮挡，查看距离的变化，可以确定雷达转向，以及range对应的角度
