### ISSUE TITLE
避障算法具体设计的讨论

### ISSUE THREAD

**Issue by sbs384** [sebuaa2019/Team201#4]
可以把机器人的直径当成一个通道宽度，然后机器人面前的90°范围内障碍物检测就可以确定通道内的障碍物，需要把障碍物的距离转化为sin和cos值，sin用来确定距离机器人的距离，cos用来确定是否在通道内，可以设定x阈值为0.4m，y阈值为机器人半径即0.25米，如果有障碍物就在其他角度内寻找没有障碍物的通道，可是通道怎么寻找呢

**Comment by woxiangquca** [comment]
可以没转一个角度就调用障碍物寻找函数，如果有就放弃，转一个角度分辨率，寻找下一个角度内的通道；没有的话就继续前行；如果360度范围内都没有可走的路径，就停止
