### ISSUE TITLE
机器人转动卡顿问题解决方法的讨论

### ISSUE THREAD

**Issue by sbs384** [sebuaa2019/Team201#5]
这个出现在沿墙走的过程中，因为检测到障碍物后转一点，就又需要转了，这个检测很频繁，其他的似乎没有这个问题

**Comment by woxiangquca** [comment]
那应该是因为每次检测采用的分辨率是1，这样的话找到一个合适的就停，然后沿墙要连续检测，就会卡

**Comment by sbs384** [comment]
那可以把分辨率*10，调大一点，这样就可以比较连续了，沿墙的时候不至于走一步检测一步
